### PR TITLE
Fix mutation assessor enrichment failure

### LINKED ISSUE #350: X,1325430,1325430,G,A gives 404
The real error is with Mutation Assessor, but the whole request should not fail because of it. Just the mutation_assessor part should be empty

### PR DESCRIPTION
**Pull request by inodb**
Fix #350 

Mutation assessor fails for X,1325430,1325430,G,A. Ignore that exception
and log as a warning instead.

### CODE REVIEW

File: service/src/main/java/org/cbioportal/genome_nexus/service/internal/VEPEnrichmentService.java [hunk 1]
```diff
@@ -32,32 +32,48 @@
...
+                Entry<String, AnnotationEnricher> enricher = it.next();
+                try {
+                    enricher.getValue().enrich(variantAnnotation);
+                } catch (Exception e) {
+
+                    LOG.warn("Failed to enrich with " + enricher.getKey() + ": " + variantAnnotation.getVariant() + " " + e.getLocalizedMessage());
+                }
+
+            }
             for (AnnotationEnricher enricher: enrichers.values())
```
Comment (onursumer) [inline service/src/main/java/org/cbioportal/genome_nexus/service/internal/VEPEnrichmentService.java]: @inodb Shouldn't we remove this `for` loop, since now we moved the enrichment to the `while` loop above?

Comment (inodb) [reply service/src/main/java/org/cbioportal/genome_nexus/service/internal/VEPEnrichmentService.java]: yes sorry just remove it 👍
