### PR TITLE
Fix the allele order for reversed strand

### LINKED ISSUE #847: Flip alleles order on reversed strand
ENST00000357654:c.1360_1361del returns "referenceAllele": "TC" and cannot find matching clinvar. This is because VEP returns "allele_string": "AG/-", and it's a reversed strand, based on this [pr](https://github.com/genome-nexus/genome-nexus/pull/806), AG is flipped to TC. But the allele order should also be flipped, the actual allele should be CT.

### PR DESCRIPTION
**Pull request by leexgh**
Fix: https://github.com/genome-nexus/genome-nexus/issues/847
To implement a proper reverse complement: first complement each nucleotide (A <-> T, C <-> G, already fixed in https://github.com/genome-nexus/genome-nexus/pull/806), then reverse the order. For example:

 - AG - complement to TC - reverse to CT
 - ATG - complement to TAC - reverse to CAT

### CODE REVIEW

File: service/src/main/java/org/cbioportal/genome_nexus/service/internal/VariantAnnotationService.java [hunk 1]
```diff
@@ -438,8 +438,22 @@ private void addAdditionalInformation(VariantAnnotation variantAnnotation, Varia
     }
 
     private void normalizeStrand(VariantAnnotation variantAnnotation) {
+        if (variantAnnotation == null) {
```
Comment (bprize15) [inline service/src/main/java/org/cbioportal/genome_nexus/service/internal/VariantAnnotationService.java]: Do we expect variantAnnotation ever being null?

**Review by bprize15 — APPROVED** [review]
One small question, otherwise LGTM

File: service/src/main/java/org/cbioportal/genome_nexus/service/internal/VariantAnnotationService.java (hunk 1 above)
Comment (leexgh) [reply service/src/main/java/org/cbioportal/genome_nexus/service/internal/VariantAnnotationService.java]: Good catch! I missed some leftover code. Deleted
